export const siteConfig = {
	title: 'FreeTheAi',
	description:
		'FreeTheAi is a free OpenAI-compatible AI API with Discord key signup, streaming chat completions, tool calling, image generation, image editing, and a live searchable model catalog.',
	site: 'https://freetheai.xyz',
	author: {
		name: 'FreeTheAi',
		url: 'https://freetheai.xyz',
	},
	socials: {
		discord: 'https://discord.gg/secrets',
		github: 'https://github.com/vibheksoni/free-ai',
		api: 'https://api.freetheai.xyz',
	},
	defaults: {
		locale: 'en_US',
		twitterCard: 'summary_large_image',
		ogImage: '/og-card.svg',
		keywords: [
			'free ai api',
			'openai compatible api',
			'openai compatible free api',
			'free openai api',
			'free llm api',
			'free ai models',
			'free ai developer api',
			'discord ai api key',
			'discord api key signup',
			'no billing ai api',
			'free chat completions api',
			'chat completions api',
			'tool calling api',
			'streaming ai api',
			'free tool calling api',
			'free image generation api',
			'free image editing api',
			'gpt image api',
			'gpt-image-2 api',
			'anthropic messages api',
			'model catalog api',
			'searchable model catalog',
			'agent api gateway',
			'developer ai tools',
			'community ai api',
			'free api key',
			'free ai gateway',
			'open model catalog api',
			'free models api',
			'700 registrations ai api',
			'2000 member ai discord',
			'glm 5.1 api',
			'15k models api',
			'ai api without daily limit',
		],
	},
};
