export const siteConfig = {
	title: 'FreeTheAi',
	description:
		'FreeTheAi is a free AI API with Discord key signup, OpenAI-compatible chat completions, xAI image and video generation, streaming, tool calling, and an expanded 15k+ model catalog previewed on the site.',
	site: 'https://freetheai.xyz',
	author: {
		name: 'FreeTheAi',
		url: 'https://freetheai.xyz',
	},
	socials: {
		discord: 'https://discord.gg/secrets',
		github: 'https://github.com/vibheksoni/free-ai',
		api: 'https://api.freetheai.xyz',
	},
	defaults: {
		locale: 'en_US',
		twitterCard: 'summary_large_image',
		ogImage: '/og-card.svg',
		keywords: [
			'free ai api',
			'openai compatible api',
			'free openai api',
			'free llm api',
			'tool calling api',
			'streaming ai api',
			'image generation api',
			'video generation api',
			'xai image api',
			'xai video api',
			'windsurf api',
			'swe-1.6 api',
			'kimi k2.6 api',
			'glm 5.1 api',
			'gpt 5.4 api',
			'claude 4.7 opus api',
			'bbl api',
			'cat api',
			'yng api',
			'glm api',
			'free glm api',
			'free gpt oss api',
			'chat completions api',
			'discord api key signup',
			'free models api',
			'15k models api',
			'open model catalog api',
			'ai api without daily limit',
			'developer ai tools',
		],
	},
};
