export const siteConfig = {
	title: 'FreeTheAi',
	description:
		'Free OpenAI-compatible API with 16,000+ models. Chat completions, streaming, tool calling, image generation, image editing, and Anthropic messages — all behind a single free key from Discord.',
	site: 'https://freetheai.xyz',
	author: {
		name: 'FreeTheAi',
		url: 'https://freetheai.xyz',
	},
	socials: {
		discord: 'https://discord.gg/secrets',
		github: 'https://github.com/vibheksoni/free-ai',
		api: 'https://api.freetheai.xyz',
	},
	defaults: {
		locale: 'en_US',
		twitterCard: 'summary_large_image',
		ogImage: '/og-card.svg',
		keywords: [
			'free ai api',
			'free openai api',
			'openai compatible api',
			'free openai compatible api',
			'free llm api',
			'free gpt api',
			'free claude api',
			'free gemini api',
			'free deepseek api',
			'free ai models',
			'free chat completions',
			'free chat completions api',
			'openai api free',
			'openai api alternative',
			'free ai api key',
			'discord ai api',
			'discord api key signup',
			'no billing ai api',
			'free streaming ai api',
			'free tool calling api',
			'free image generation api',
			'free image editing api',
			'free gpt image api',
			'gpt-image-2 free',
			'anthropic messages api free',
			'free ai gateway',
			'ai model catalog',
			'free ai for developers',
			'free ai for students',
			'agent framework api',
			'16000 models api',
			'free api no daily limit',
			'ai api without credit card',
			'free llm access',
			'open model api',
			'free ai inference',
		],
	},
};
